// CDCR and California state facility list used by the intake form dropdown.
export const CA_FACILITIES = [
  "Avenal State Prison",
  "Calipatria State Prison",
  "California Correctional Institution (Tehachapi)",
  "California Health Care Facility (Stockton)",
  "California Institution for Men (Chino)",
  "California Institution for Women (Corona)",
  "California Medical Facility (Vacaville)",
  "California Men's Colony (San Luis Obispo)",
  "California Rehabilitation Center (Norco)",
  "California State Prison, Corcoran",
  "California State Prison, Los Angeles County (Lancaster)",
  "California State Prison, Sacramento (New Folsom)",
  "California State Prison, Solano",
  "Centinela State Prison",
  "Central California Women's Facility (Chowchilla)",
  "Chuckawalla Valley State Prison",
  "Coalinga State Hospital",
  "Correctional Training Facility (Soledad)",
  "Folsom State Prison",
  "High Desert State Prison (Susanville)",
  "Ironwood State Prison",
  "Kern Valley State Prison",
  "Kings County Correctional Facility",
  "LA County Transitional Facility",
  "Mule Creek State Prison",
  "North Kern State Prison",
  "Pelican Bay State Prison",
  "Pleasant Valley State Prison",
  "R.J. Donovan Correctional Facility (San Diego)",
  "Salinas Valley State Prison",
  "San Quentin Rehabilitation Center",
  "Sierra Conservation Center",
  "Substance Abuse Treatment Facility (Corcoran)",
  "Taft Correctional Institution",
  "Valley State Prison (Chowchilla)",
  "Wasco State Prison",
  "Other / Not listed",
] as const;

export const CA_COUNTIES = [
  "Alameda", "Alpine", "Amador", "Butte", "Calaveras", "Colusa", "Contra Costa",
  "Del Norte", "El Dorado", "Fresno", "Glenn", "Humboldt", "Imperial", "Inyo",
  "Kern", "Kings", "Lake", "Lassen", "Los Angeles", "Madera", "Marin", "Mariposa",
  "Mendocino", "Merced", "Modoc", "Mono", "Monterey", "Napa", "Nevada", "Orange",
  "Placer", "Plumas", "Riverside", "Sacramento", "San Benito", "San Bernardino",
  "San Diego", "San Francisco", "San Joaquin", "San Luis Obispo", "San Mateo",
  "Santa Barbara", "Santa Clara", "Santa Cruz", "Shasta", "Sierra", "Siskiyou",
  "Solano", "Sonoma", "Stanislaus", "Sutter", "Tehama", "Trinity", "Tulare",
  "Tuolumne", "Ventura", "Yolo", "Yuba",
] as const;

export const REFERRAL_SOURCES = [
  "Family Member or Friend",
  "Legal Professional",
  "Prison Staff or Counselor",
  "Online Search",
  "Social Media",
  "Nonprofit Organization",
  "Other",
] as const;
